class AccountAlias < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[AccountAlias, AccountAlias::ActiveRecord_Relation]

  attr_accessor id (): Integer
  attr_accessor account_id (): Integer
  attr_accessor acct (): String
  attr_accessor uri (): String
  attr_accessor created_at (): Time
  attr_accessor updated_at (): Time

  def account: () -> Account
end

class AccountAlias::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[AccountAlias]
  include Enumerable[AccountAlias, self]
end

class AccountAlias::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
