class FollowRequest < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[FollowRequest, FollowRequest::ActiveRecord_Relation]

  attr_accessor id (): Integer
  attr_accessor created_at (): Time
  attr_accessor updated_at (): Time
  attr_accessor account_id (): Integer
  attr_accessor target_account_id (): Integer
  attr_accessor show_reblogs (): TrueClass | FalseClass
  attr_accessor uri (): String

  def notification: () -> Notification
  def account: () -> Account
  def target_account: () -> Account
end

class FollowRequest::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[FollowRequest]
  include Enumerable[FollowRequest, self]
end

class FollowRequest::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
