module Rails
  def self.root: () -> Pathname
  def self.application: () -> Rails::Application
  def self.configuration: () -> Rails::Application::Configuration
  overload def self.env: () -> ActiveSupport::StringInquirer

  module Dom
    module Testing
      module Assertions
      end
    end
  end
end

class Rails::Application
  def routes: () -> untyped

  class Configuration
    def x: () -> Rails::Application::Configuration::Custom

    class Custom
      def otp_secret: () -> String
    end
  end
end
